//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseContent
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class concentrate_testEntities4 : DbContext
    {
        public concentrate_testEntities4()
            : base("name=concentrate_testEntities4")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<bouncingballscore> bouncingballscores { get; set; }
        public DbSet<bulbtestscore> bulbtestscores { get; set; }
        public DbSet<memorytestorderscore> memorytestorderscores { get; set; }
        public DbSet<mindtestscore> mindtestscores { get; set; }
        public DbSet<mindtestscoreseasy> mindtestscoreseasies { get; set; }
        public DbSet<mindtestscoreshard> mindtestscoreshards { get; set; }
        public DbSet<mindtestscoresmedium> mindtestscoresmediums { get; set; }
        public DbSet<mindtestscoresveryhard> mindtestscoresveryhards { get; set; }
        public DbSet<reactiontestscore> reactiontestscores { get; set; }
        public DbSet<user> users { get; set; }
    }
}
