//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseContent
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public user()
        {
            this.bouncingballscores = new HashSet<bouncingballscore>();
            this.bulbtestscores = new HashSet<bulbtestscore>();
            this.memorytestorderscores = new HashSet<memorytestorderscore>();
            this.mindtestscores = new HashSet<mindtestscore>();
            this.mindtestscoreseasies = new HashSet<mindtestscoreseasy>();
            this.mindtestscoreshards = new HashSet<mindtestscoreshard>();
            this.mindtestscoresmediums = new HashSet<mindtestscoresmedium>();
            this.mindtestscoresveryhards = new HashSet<mindtestscoresveryhard>();
            this.reactiontestscores = new HashSet<reactiontestscore>();
        }
    
        public int Id { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
    
        public virtual ICollection<bouncingballscore> bouncingballscores { get; set; }
        public virtual ICollection<bulbtestscore> bulbtestscores { get; set; }
        public virtual ICollection<memorytestorderscore> memorytestorderscores { get; set; }
        public virtual ICollection<mindtestscore> mindtestscores { get; set; }
        public virtual ICollection<mindtestscoreseasy> mindtestscoreseasies { get; set; }
        public virtual ICollection<mindtestscoreshard> mindtestscoreshards { get; set; }
        public virtual ICollection<mindtestscoresmedium> mindtestscoresmediums { get; set; }
        public virtual ICollection<mindtestscoresveryhard> mindtestscoresveryhards { get; set; }
        public virtual ICollection<reactiontestscore> reactiontestscores { get; set; }
    }
}
